# Generated by Django 2.2.1 on 2019-05-25 21:48

import animals.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='serial_number',
            field=models.CharField(max_length=10, validators=[animals.validators.SerialNumberValidator()]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vaccine_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vaccine_1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vaccine_2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vaccine_2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vaccine_3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vaccine_3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vaccine_4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='vaccine_4_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
